Config = {}
Config.ShowBlips = true -- Toggle this to true or false to show/hide blips
Config.Cooldown = 120 -- Cooldown in seconds (2 minutes)
Config.PoliceCallChance = 30      -- Selling items police alert chance
Config.BuyPoliceCallChance = 30   -- Buying items police alert chance (can be different %)


Config.SellLocations = {
    {
        vehicle = 'taco', -- or any other valid GTA vehicle model
        coords = vector4(-895.93, -2035.28, 9.3, 18.48),
        blip = {
            sprite = 680,
            color = 2, -- Must all be the same colour :P
            scale = 0.8,
            label = "Pedvend LTD"
        }
    },
    {
        vehicle = 'taco',
        coords = vector4(1087.32, -340.72, 67.24, 121.46),
        blip = {
            sprite = 680,
            color = 2,
            scale = 0.8,
            label = "Pedvend LTD"
        }
    },
    {
        vehicle = 'taco',
        coords = vector4(-1823.81, 810.64, 139.12, 215.78),
        blip = {
            sprite = 680,
            color = 2,
            scale = 0.8,
            label = "Pedvend LTD"
        }
    },
    {
        vehicle = 'taco',
        coords = vector4(3.13, 6434.87, 31.43, 223.9),
        blip = {
            sprite = 680,
            color = 2,
            scale = 0.8,
            label = "Pedvend LTD"
        }
    }
    -- Add more locations as needed
}

Config.Items = {
    Drugs = {
        {name = "joint", label = "Joint", price = 5},
        {name = "coke_brick", label = "Coke Brick", price = 180},
        {name = "weed_brick", label = "Weed Brick", price = 70},
        {name = "coke_small_brick", label = "Small Coke Brick", price = 90},
        {name = "oxy", label = "Oxy", price = 40},
        {name = "meth_package", label = "Meth Package", price = 190},
    },
    Weapons = {
        {name = "weapon_dagger", label = "Dagger", price = 50},
        {name = "weapon_bat", label = "Bat", price = 30},
        {name = "weapon_bottle", label = "Broken Bottle", price = 5},
        {name = "weapon_crowbar", label = "Crowbar", price = 40},
        {name = "weapon_flashlight", label = "Flashlight", price = 15},
        {name = "weapon_golfclub", label = "Golfclub", price = 25},
        {name = "weapon_hammer", label = "Hammer", price = 35},
        {name = "weapon_hatchet", label = "Hatchet", price = 45},
        {name = "weapon_knuckle", label = "Knuckle", price = 20},
        {name = "weapon_knife", label = "Knife", price = 55},
        {name = "weapon_machete", label = "Machete", price = 60},
        {name = "weapon_switchblade", label = "Switchblade", price = 50},
        {name = "weapon_nightstick", label = "Nightstick", price = 30},
        {name = "weapon_wrench", label = "Wrench", price = 25},
        {name = "weapon_battleaxe", label = "Battle Axe", price = 70},
        {name = "weapon_poolcue", label = "Poolcue", price = 20},
        {name = "weapon_garbagebag", label = "Garbage Bag", price = 10},
        {name = "weapon_handcuffs", label = "Handcuffs", price = 25},
        {name = "weapon_bread", label = "Baquette", price = 5},
        {name = "weapon_stone_hatchet", label = "Stone Hatchet", price = 50},
        {name = "weapon_candycane", label = "Candy Cane", price = 5},
        {name = "weapon_pistol", label = "Walther P99", price = 100},
        {name = "weapon_pistol_mk2", label = "Pistol Mk II", price = 120},
        {name = "weapon_combatpistol", label = "Combat Pistol", price = 150},
        {name = "weapon_appistol", label = "AP Pistol", price = 160},
        {name = "weapon_stungun", label = "Taser", price = 80},
        {name = "weapon_pistol50", label = "Pistol .50", price = 200},
        {name = "weapon_snspistol", label = "SNS Pistol", price = 90},
        {name = "weapon_heavypistol", label = "Heavy Pistol", price = 130},
        {name = "weapon_vintagepistol", label = "Vintage Pistol", price = 110},
        {name = "weapon_flaregun", label = "Flare Gun", price = 70},
        {name = "weapon_marksmanpistol", label = "Marksman Pistol", price = 140},
        {name = "weapon_revolver", label = "Revolver", price = 180},
        {name = "weapon_revolver_mk2", label = "Violence", price = 190},
        {name = "weapon_doubleaction", label = "Double Action Revolver", price = 170},
        {name = "weapon_snspistol_mk2", label = "SNS Pistol Mk II", price = 95},
        {name = "weapon_raypistol", label = "Up-n-Atomizer", price = 210},
        {name = "weapon_ceramicpistol", label = "Ceramic Pistol", price = 115},
        {name = "weapon_navyrevolver", label = "Navy Revolver", price = 175},
        {name = "weapon_gadgetpistol", label = "Perico Pistol", price = 125},
        {name = "weapon_pistolxm3", label = "Pistol XM3", price = 135},
        {name = "weapon_microsmg", label = "Micro SMG", price = 220},
        {name = "weapon_smg", label = "SMG", price = 240},
        {name = "weapon_smg_mk2", label = "SMG Mk II", price = 260},
        {name = "weapon_assaultsmg", label = "Assault SMG", price = 280},
        {name = "weapon_combatpdw", label = "Combat PDW", price = 300},
        {name = "weapon_machinepistol", label = "Tec-9", price = 210},
        {name = "weapon_minismg", label = "Mini SMG", price = 230},
        {name = "weapon_raycarbine", label = "Unholy Hellbringer", price = 320},
        {name = "weapon_pumpshotgun", label = "Pump Shotgun", price = 250},
        {name = "weapon_sawnoffshotgun", label = "Sawn-off Shotgun", price = 230},
        {name = "weapon_assaultshotgun", label = "Assault Shotgun", price = 270},
        {name = "weapon_bullpupshotgun", label = "Bullpup Shotgun", price = 260},
        {name = "weapon_musket", label = "Musket", price = 240},
        {name = "weapon_heavyshotgun", label = "Heavy Shotgun", price = 290},
        {name = "weapon_dbshotgun", label = "Double-barrel Shotgun", price = 280},
        {name = "weapon_autoshotgun", label = "Auto Shotgun", price = 300},
        {name = "weapon_pumpshotgun_mk2", label = "Pumpshotgun Mk II", price = 270},
        {name = "weapon_combatshotgun", label = "Combat Shotgun", price = 310},
        {name = "weapon_assaultrifle", label = "Assault Rifle", price = 350},
        {name = "weapon_assaultrifle_mk2", label = "Assault Rifle Mk II", price = 370},
        {name = "weapon_carbinerifle", label = "Carbine Rifle", price = 360},
        {name = "weapon_carbinerifle_mk2", label = "Carbine Rifle Mk II", price = 380},
        {name = "weapon_advancedrifle", label = "Advanced Rifle", price = 390},
        {name = "weapon_specialcarbine", label = "Special Carbine", price = 400},
        {name = "weapon_bullpuprifle", label = "Bullpup Rifle", price = 410},
        {name = "weapon_compactrifle", label = "Compact Rifle", price = 420},
        {name = "weapon_specialcarbine_mk2", label = "Special Carbine Mk II", price = 430},
        {name = "weapon_bullpuprifle_mk2", label = "Bullpup Rifle Mk II", price = 440},
        {name = "weapon_militaryrifle", label = "Military Rifle", price = 450},
        {name = "weapon_mg", label = "Machinegun", price = 460},
        {name = "weapon_combatmg", label = "Combat MG", price = 470},
        {name = "weapon_gusenberg", label = "Thompson SMG", price = 480},
        {name = "weapon_combatmg_mk2", label = "Combat MG Mk II", price = 490},
        {name = "weapon_sniperrifle", label = "Sniper Rifle", price = 500},
        {name = "weapon_heavysniper", label = "Heavy Sniper", price = 520},
        {name = "weapon_marksmanrifle", label = "Marksman Rifle", price = 530},
        {name = "weapon_heavysniper_mk2", label = "Heavy Sniper Mk II", price = 550},
        {name = "weapon_marksmanrifle_mk2", label = "Marksman Rifle Mk II", price = 560},
        {name = "weapon_rpg", label = "RPG", price = 570},
        {name = "weapon_grenadelauncher", label = "Grenade Launcher", price = 580},
        {name = "weapon_minigun", label = "Minigun", price = 600},
        {name = "weapon_firework", label = "Firework Launcher", price = 610},
        {name = "weapon_railgun", label = "Railgun", price = 620},
        {name = "weapon_hominglauncher", label = "Homing Launcher", price = 640},
        {name = "weapon_compactlauncher", label = "Compact Launcher", price = 650},
        {name = "weapon_rayminigun", label = "Widowmaker", price = 660},
        {name = "weapon_grenade", label = "Grenade", price = 670},
        {name = "weapon_molotov", label = "Molotov", price = 690},
        {name = "weapon_stickybomb", label = "C4", price = 700},
        {name = "weapon_proxmine", label = "Proxmine Grenade", price = 710},
        {name = "weapon_pipebomb", label = "Pipe Bomb", price = 730},
        {name = "weapon_flare", label = "Flare pistol", price = 760},
        {name = "weapon_petrolcan", label = "Petrol Can", price = 100},
        {name = "weapon_fireextinguisher", label = "Fire Extinguisher", price = 20},
    },
    Attachments = {
        {name = "clip_attachment", label = "Clip", price = 20},
        {name = "drum_attachment", label = "Drum", price = 30},
        {name = "flashlight_attachment", label = "Flashlight", price = 25},
        {name = "suppressor_attachment", label = "Suppressor", price = 40},
        {name = "smallscope_attachment", label = "Small Scope", price = 35},
        {name = "medscope_attachment", label = "Medium Scope", price = 45},
        {name = "largescope_attachment", label = "Large Scope", price = 50},
        {name = "holoscope_attachment", label = "Holo Scope", price = 55},
        {name = "advscope_attachment", label = "Advanced Scope", price = 60},
        {name = "nvscope_attachment", label = "Night Vision Scope", price = 65},
        {name = "thermalscope_attachment", label = "Thermal Scope", price = 70},
        {name = "flat_muzzle_brake", label = "Flat Muzzle Brake", price = 75},
        {name = "tactical_muzzle_brake", label = "Tactical Muzzle Brake", price = 80},
        {name = "fat_end_muzzle_brake", label = "Fat End Muzzle Brake", price = 85},
        {name = "precision_muzzle_brake", label = "Precision Muzzle Brake", price = 90},
        {name = "heavy_duty_muzzle_brake", label = "HD Muzzle Brake", price = 95},
        {name = "slanted_muzzle_brake", label = "Slanted Muzzle Brake", price = 100},
        {name = "split_end_muzzle_brake", label = "Split End Muzzle Brake", price = 105},
        {name = "squared_muzzle_brake", label = "Squared Muzzle Brake", price = 110},
        {name = "bellend_muzzle_brake", label = "Bellend Muzzle Brake", price = 115},
        {name = "barrel_attachment", label = "Barrel", price = 120},
        {name = "grip_attachment", label = "Grip", price = 125},
        {name = "comp_attachment", label = "Compensator", price = 130},
        {name = "digicamo_attachment", label = "Digital Camo", price = 140},
        {name = "brushcamo_attachment", label = "Brushstroke Camo", price = 145},
        {name = "woodcamo_attachment", label = "Woodland Camo", price = 150},
        {name = "skullcamo_attachment", label = "Skull Camo", price = 155},
        {name = "sessantacamo_attachment", label = "Sessanta Nove Camo", price = 160},
        {name = "perseuscamo_attachment", label = "Perseus Camo", price = 165},
        {name = "leopardcamo_attachment", label = "Leopard Camo", price = 170},
        {name = "zebracamo_attachment", label = "Zebra Camo", price = 175},
        {name = "geocamo_attachment", label = "Geometric Camo", price = 180},
        {name = "boomcamo_attachment", label = "Boom Camo", price = 185},
        {name = "patriotcamo_attachment", label = "Patriot Camo", price = 190},
    },
    Cards = {
        {name = "id_card", label = "ID Card", price = 5},
        {name = "driver_license", label = "Driver's License", price = 10},
        {name = "lawyerpass", label = "Lawyer Pass", price = 15},
        {name = "bank_card", label = "Bank Card", price = 25},
        {name = "security_card_01", label = "Security Card A", price = 30},
        {name = "security_card_02", label = "Security Card B", price = 35},
    },
    Ammo = {
        {name = "pistol_ammo", label = "Pistol Ammo", price = 10},
        {name = "rifle_ammo", label = "Rifle Ammo", price = 15},
        {name = "smg_ammo", label = "SMG Ammo", price = 12},
        {name = "shotgun_ammo", label = "Shotgun Ammo", price = 14},
        {name = "mg_ammo", label = "MG Ammo", price = 18},
    },
    Materials = {
        {name = "plastic", label = "Plastic", price = 1},
        {name = "metalscrap", label = "Metal Scrap", price = 2},
        {name = "copper", label = "Copper", price = 3},
        {name = "aluminum", label = "Aluminium", price = 4},
        {name = "iron", label = "Iron", price = 5},
        {name = "steel", label = "Steel", price = 6},
        {name = "rubber", label = "Rubber", price = 2},
        {name = "glass", label = "Glass", price = 3},
    },
    Tools = {
        {name = "lockpick", label = "Lockpick", price = 10},
        {name = "advancedlockpick", label = "Advanced Lockpick", price = 120},
        {name = "screwdriverset", label = "Toolkit", price = 95},
        {name = "drill", label = "Drill", price = 165},
    },
    MechanicParts = {
        {name = "veh_toolbox", label = "Toolbox", price = 95},
        {name = "veh_armor", label = "Armor", price = 150},
        {name = "veh_brakes", label = "Brakes", price = 140},
        {name = "veh_engine", label = "Engine", price = 160},
        {name = "veh_suspension", label = "Suspension", price = 135},
        {name = "veh_transmission", label = "Transmission", price = 145},
        {name = "veh_turbo", label = "Turbo", price = 155},
        {name = "ls_jackstand", label = "Jack Stands", price = 325},
    },
    Communication = {
        {name = "phone", label = "Phone", price = 200},
        {name = "radio", label = "Radio", price = 150},
        {name = "laptop", label = "Laptop", price = 350},
        {name = "tablet", label = "Tablet", price = 220},
    },
    TheftAndJewelry = {
        {name = "rolex", label = "Golden Watch", price = 200},
        {name = "diamond_ring", label = "Diamond Ring", price = 300},
        {name = "diamond", label = "Diamond", price = 250},
        {name = "goldchain", label = "Golden Chain", price = 220},
        {name = "goldbar", label = "Gold Bar", price = 700},
        {name = "tenkgoldchain", label = "10k Goldhcain", price = 500},
    },
    LabKeys = {
        {name = "methkey", label = "Meth Lab Access Key", price = 8000},
        {name = "weedkey", label = "Weed Lab Access Key", price = 5000},
        {name = "cokekey", label = "Coke Lab Access Key", price = 7500},
    },
    VehicleParts = {
        {name = "stock_transmission", label = "Stock Transmission", price = 30},
        {name = "race_transmission", label = "Race Transmission", price = 60},
        {name = "stock_suspension", label = "Stock Suspension", price = 35},
        {name = "race_suspension", label = "Race Suspension", price = 70},
        {name = "stock_oil", label = "Stock Oil", price = 10},
        {name = "shell_oil", label = "Shell Oil", price = 15},
        {name = "stock_engine", label = "Stock Engine", price = 50},
        {name = "v8engine", label = "V8 Engine", price = 100},
        {name = "turbo_lvl_1", label = "Garret STG-1", price = 250},
        {name = "turbo_lvl_2", label = "Garret STG-2", price = 300},
        {name = "turbo_lvl_3", label = "Garret STG-3", price = 500},
    },
    Fireworks = {
        {name = "firework1", label = "Firework 1", price = 110},
        {name = "firework2", label = "Firework 2", price = 115},
        {name = "firework3", label = "Firework 3", price = 120},
        {name = "firework4", label = "Firework 4", price = 125},
    },
    Medical = {
        {name = "bandage", label = "Bandage", price = 10},
        {name = "ifaks", label = "Ifaks", price = 385},
        {name = "firstaid", label = "First Aid Kit", price = 120},
        {name = "painkillers", label = "Painkillers", price = 15},
    }

    -- Add more categories here
    -- {name = "item_name", label = "Item Label", price = 10}, -- NOTE: THESE PRICES ARE DOUBLED FOR PURCHASING FROM THE SHOP. THESE ARE SELL PRICES.
}
